# Generated by Django 5.1.3 on 2024-11-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MACD_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('vwap', models.FloatField()),
                ('trade_count', models.IntegerField()),
                ('macd', models.FloatField()),
                ('signal_line', models.FloatField()),
                ('macd_histogram', models.FloatField()),
            ],
        ),
    ]
